ALTER TABLE scalling_strategy.opsp_format_bhag MODIFY COLUMN description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE scalling_strategy.opsp_format_profit_per_x MODIFY COLUMN profit_per_x_definition TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE scalling_strategy.opsp_format_territories ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_territories CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_cultures MODIFY COLUMN culture_name varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE scalling_strategy.opsp_format_cultures MODIFY COLUMN culture_description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE scalling_strategy.opsp_format_consistent_actions ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_consistent_actions CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_bhag ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_bhag CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_brand_promises ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_brand_promises CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_central_clients ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_central_clients CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_key_competencies ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_key_competencies CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_core_values ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_core_values CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_cultures ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_cultures CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_factor_x ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_factor_x CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_fdt ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_fdt CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;	
ALTER TABLE scalling_strategy.opsp_format_flywheels ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_flywheels CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_goals ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_goals CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_kpi_balances ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_kpi_balances CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_profit_per_x ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_profit_per_x CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_purposes ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_purposes CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_7_stratas ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_7_stratas CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_visions ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_visions CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
ALTER TABLE scalling_strategy.opsp_format_players_a ADD id_entity varchar(50) NULL;
ALTER TABLE scalling_strategy.opsp_format_players_a CHANGE id_entity id_entity varchar(50) NULL AFTER id_company;
